// This file is generated automatically by Next.js
// Do not edit this file manually

<<<<<<< HEAD
type AppRoutes = "/" | "/campeonatos" | "/campeonatos/adicionar-campeonato" | "/campeonatos/historico-partidas" | "/campeonatos/registrar-partida" | "/login" | "/register"
type PageRoutes = never
type LayoutRoutes = "/"
=======
type AppRoutes = "/" | "/admin" | "/admin/campeonatos" | "/admin/noticias" | "/admin/noticias/cadastrarNoticia" | "/aluno" | "/login" | "/register"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
>>>>>>> ab42ab5d93d49a172cb26a9cd336c18fb3b79ad0
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
<<<<<<< HEAD
  "/campeonatos": {}
  "/campeonatos/adicionar-campeonato": {}
  "/campeonatos/historico-partidas": {}
  "/campeonatos/registrar-partida": {}
=======
  "/admin": {}
  "/admin/campeonatos": {}
  "/admin/noticias": {}
  "/admin/noticias/cadastrarNoticia": {}
  "/aluno": {}
>>>>>>> ab42ab5d93d49a172cb26a9cd336c18fb3b79ad0
  "/login": {}
  "/register": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
<<<<<<< HEAD
=======
  "/admin": never
>>>>>>> ab42ab5d93d49a172cb26a9cd336c18fb3b79ad0
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
